connection: Data Source=localhost;Initial Catalog=tempdb;Integrated Security=False;User ID=sa;Password=SqlServerIs#1;Encrypt=False;Application Name="Stored Procedure Data Context Generator"
csharp:
  namespace: Pingmint.CodeGen.Sql
  class: Proxy
databases:
  - tempdb:
      class: TempDb
      statements:
        - name: GetSysTypes
          text: SELECT name FROM sys.types
        - name: GetTableTypes
          text: |
            SELECT T.name, T.type_table_object_id, S.name as [Schema_Name]
            FROM sys.table_types AS T
            INNER JOIN sys.schemas as S ON (T.schema_id = S.schema_id)
            ORDER BY S.name, T.name
        - name: GetObsoleteProcedures
          text: |
            SELECT E.name, CAST(E.value as VARCHAR(MAX)) AS [value], E.major_id
            FROM sys.procedures AS P
            INNER JOIN sys.extended_properties AS E ON (P.object_id = E.major_id)
            WHERE E.name = 'Obsolete'
        - name: GetProcGenHintProcedures
          text: |
            SELECT CAST(E.value as VARCHAR(MAX)) AS [value], E.major_id
            FROM sys.procedures AS P
            INNER JOIN sys.extended_properties AS E ON (P.object_id = E.major_id)
            WHERE E.name = @hint_name
          parameters:
            - name: hint_name
              type: varchar
        - name: GetExtendedPropertiesForProcedure
          text: |
            SELECT CAST(e.value as varchar(max)) as [value]
            FROM sys.fn_listextendedproperty('ProcGen_ReinterpretColumns', 'SCHEMA', @schema, 'PROCEDURE', @proc, NULL, NULL) AS E
          parameters:
            - name: schema
              type: varchar
            - name: proc
              type: varchar
        - name: GetProceduresForSchema
          text: |
            SELECT P.name, P.object_id, S.name as [Schema_Name]
            FROM sys.procedures AS P
            INNER JOIN sys.schemas as S ON (P.schema_id = S.schema_id)
            WHERE S.name = @schema ORDER BY P.name
          parameters:
            - name: schema
              type: varchar
            - name: proc
              type: varchar
        - name: DmDescribeFirstResultSetForObject
          text: |
            SELECT D.name, D.system_type_id, D.is_nullable, D.column_ordinal, T.name as [Type_Name]
            FROM sys.dm_exec_describe_first_result_set_for_object(@objectid, NULL) AS D
            JOIN sys.types AS T ON (D.system_type_id = T.system_type_id)
            WHERE T.name <> 'sysname' ORDER BY D.column_ordinal
          parameters:
            - name: objectid
              type: int
        - name: DmDescribeFirstResultSet
          text: |
            SELECT D.name, D.system_type_id, D.is_nullable, D.column_ordinal, T.name as [type_name]
            FROM sys.dm_exec_describe_first_result_set(@text, NULL, NULL) AS D
            JOIN sys.types AS T ON (D.system_type_id = T.system_type_id AND T.user_type_id = D.system_type_id)
            ORDER BY D.column_ordinal
          parameters:
            - name: text
              type: varchar
        - name: GetSysType
          text: |
            SELECT system_type_id, is_table_type, name
            FROM sys.types where system_type_id = @id
          parameters:
            - name: id
              type: int
        - name: GetParametersForObject
          text: |
            SELECT P.parameter_id, P.system_type_id, P.name, P.is_output, P.max_length, T.is_table_type, T.name as [Type_Name]
            FROM sys.parameters AS P
            JOIN sys.types AS T ON (P.system_type_id = T.system_type_id AND P.user_type_id = T.user_type_id)
            WHERE P.object_id = @id
          parameters:
            - name: id
              type: int
        - name: GetTableTypeColumns
          text: |
            SELECT C.is_nullable, C.max_length, C.name, t.name as [Type_Name]
            from sys.columns as C join sys.types T ON (C.system_type_id = T.system_type_id)
            where C.object_id = @id and t.name <> 'sysname'
            order by c.column_id
          parameters:
            - name: id
              type: int
